version: '2.1'
orbs:
  node: circleci/node@5.2.0
jobs:
  lint:
    executor:
      name: node/default
      tag: '20.11.1'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run lint
  deploy:
    executor:
      name: node/default
      tag: '20.11.1'
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Create credentials file from env var
          command: echo "${GOOGLE_APPLICATION_CREDENTIALS_BASE64}" | base64 --decode > "google-application-credentials.json"
      - run:
          name: Deploy to Firebase hosting
          environment:
            GOOGLE_APPLICATION_CREDENTIALS: google-application-credentials.json
          command: npm run deploy --only=hosting
      - run:
          name: Remove credentials file
          when: always
          command: rm google-application-credentials.json
workflows:
  test_and_deploy:
    jobs:
      - lint
      - deploy:
          requires:
            - lint
          filters:
            branches:
              only: main
