version: '2.1'
orbs:
  node: circleci/node@5.2.0
jobs:
  test:
    executor:
      name: node/default
      tag: '20.11.1'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run lint
  deploy:
    executor:
      name: node/default
      tag: '20.11.1'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: echo "${GOOGLE_APPLICATION_CREDENTIALS_BASE64}" | base64 --decode > "google-application-credentials.json"
      - run:
          environment:
            GOOGLE_APPLICATION_CREDENTIALS: google-application-credentials.json
          command: npm run deploy
workflows:
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
